version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: ./Dockerfile
        ports:
            - "443:443"
        networks:
            - hde-oliv
        volumes:
            - wordpress_vol:/www
        env_file: ./.env
        depends_on:
            - wordpress
        restart: always

    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: ./Dockerfile
        networks:
            - hde-oliv
        volumes:
            - wordpress_vol:/www
        env_file: ./.env
        depends_on:
            - mariadb
        restart: always

    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: ./Dockerfile
        networks:
            - hde-oliv
        volumes:
            - mariadb_vol:/var/lib/mysql
        env_file: ./.env
        restart: always

networks:
    hde-oliv:
        name: "hde-oliv"
        driver: bridge

volumes:
    wordpress_vol:
        name: "wordpress_vol"
        driver: local
        driver_opts:
            type: none
            device: /home/hde-oliv/data/wordpress/
            o: bind

    mariadb_vol:
        name: "mariadb_vol"
        driver: local
        driver_opts:
            type: none
            device: /home/hde-oliv/data/mariadb/
            o: bind
