version: '3'

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "443:443"
    networks:
      - hde-oliv
    volumes:
      - wordpress_vol:/www

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - hde-oliv
    volumes:
      - wordpress_vol:/usr/share/webapps/wordpress

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - hde-oliv
    volumes:
      - mariadb_vol:/var/lib/mysql

networks:
  hde-oliv:
    name: "hde-oliv"
    driver: bridge

volumes:
  wordpress_vol:
    name: "wordpress_vol"
    driver_opts:
      o: bind
      type: none
      device: /home/hde-oliv/data

  mariadb_vol:
    name: "mariadb_vol"
    driver_opts:
      o: bind
      type: none
      device: /home/hde-oliv/data
